defaults: 
  - _self_
  - model: mobilenetv2
  - dataset : cifar10

system : 
  seed: 215 
  cuda: True
  num_workers: 4
  pin_memory : True

params : 
  batch_size: 32
  epoch: 
    pretrained: 50
    scratch: 150
  lr: 
    scratch: 1e-3
    pretrained: 1e-5
  momentum: 0.9
  step : 50
  gamma : 0.1
  scheduler : None

attack : 
  bshape: 'square'
  blabel: 0
  numbit : [8]
  const1: 0.5
  const2: 0.5
  numrun: -1
  bratio : 0.01